# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath E:/FPGA/modelsim/win64
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config  -id {Vivado 12-5495}  -string {{WARNING: [Vivado 12-5495] Detected incompatible modelsim simulator installation version '10.6d'! The supported simulator version for the current Vivado release is '10.6c'.}}  -suppress 
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/F_prj/plate_recognization/plate_recognization.cache/wt [current_project]
set_property parent.project_path F:/F_prj/plate_recognization/plate_recognization.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/F_prj/plate_recognization/plate_recognization.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/Get_EigenValue.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/sobel/Sobel_Edge_Detector.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/dilation/VIP_Bit_Dilation_Detector.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/erosion/VIP_Bit_Erosion_Detector.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/projection/VIP_horizon_projection.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/projection/VIP_vertical_projection.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/add_char.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/add_grid.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/binarization/binarization.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/char_binarization.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/char_horizon_projection.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/char_vertical_projection.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/clk_div.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/cmos_capture_data.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ddr3_top/ddr3_fifo_ctrl.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ddr3_top/ddr3_rw.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ddr3_top/ddr3_top.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/i2c_dri.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/i2c_ov5640_rgb565_cfg.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/image_process.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/lcd_driver.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/lcd_rgb_top.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/line_shift_ram_8bit.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/matrix_generate_3x3_1bit.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/matrix_generate_3x3_8bit.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/ov5640_dri.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/picture_size.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/rd_id.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/rgb2ycbcr.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/template_matching.v
  C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_fun4_lcd.v
}
read_ip -quiet F:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/wr_fifo/wr_fifo.xci
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/wr_fifo/wr_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/wr_fifo/wr_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/wr_fifo/wr_fifo_ooc.xdc]

read_ip -quiet F:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/rd_fifo/rd_fifo.xci
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/rd_fifo/rd_fifo.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/rd_fifo/rd_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/rd_fifo/rd_fifo_ooc.xdc]

read_ip -quiet F:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet F:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/cordic/cordic.xci
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/cordic/cordic_ooc.xdc]

read_ip -quiet F:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet F:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet F:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/projection_ram/projection_ram.xci
set_property used_in_implementation false [get_files -all f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/projection_ram/projection_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ov5640_fun4_lcd -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ov5640_fun4_lcd.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ov5640_fun4_lcd_utilization_synth.rpt -pb ov5640_fun4_lcd_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
