# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/projection_ram/projection_ram.xci
# IP: The module: 'projection_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/projection_ram/projection_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'projection_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/projection_ram/projection_ram.xci
# IP: The module: 'projection_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/F_prj/plate_recognization/plate_recognization.srcs/sources_1/ip/projection_ram/projection_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'projection_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
