######################################################################
#
# File name : ov5640_fun4_lcd_compile.do
# Created on: Thu Mar 28 19:44:41 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\FPGA\\modelsim\\win64\\vlib modelsim_lib/work
E:\\FPGA\\modelsim\\win64\\vlib modelsim_lib/msim

E:\\FPGA\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\FPGA\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\FPGA\\modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../plate_recognization.srcs/sources_1/ip/clk_wiz_0" \
"../../../../plate_recognization.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../plate_recognization.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../plate_recognization.srcs/sources_1/ip/wr_fifo/sim/wr_fifo.v" \
"../../../../plate_recognization.srcs/sources_1/ip/rd_fifo/sim/rd_fifo.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_arb_select.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_common.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_bank_state.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_col_mach.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_mc.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_common.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_std.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_ddr_skip_calib_tap.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/phy/mig_7series_v4_2_poc_top.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_top.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/mig_7series_0_mig_sim.v" \
"../../../../plate_recognization.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/rtl/mig_7series_0.v" \
"../../../../plate_recognization.srcs/sources_1/ip/projection_ram/sim/projection_ram.v" \
"../../../../plate_recognization.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \

E:\\FPGA\\modelsim\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../plate_recognization.srcs/sources_1/ip/cordic/sim/cordic.vhd" \

E:\\FPGA\\modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../plate_recognization.srcs/sources_1/ip/clk_wiz_0" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/Get_EigenValue.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/sobel/Sobel_Edge_Detector.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/dilation/VIP_Bit_Dilation_Detector.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/erosion/VIP_Bit_Erosion_Detector.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/projection/VIP_horizon_projection.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/projection/VIP_vertical_projection.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/add_char.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/add_grid.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/binarization/binarization.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/char_binarization.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/char_horizon_projection.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/char_vertical_projection.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/clk_div.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/cmos_capture_data.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ddr3_top/ddr3_fifo_ctrl.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ddr3_top/ddr3_rw.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ddr3_top/ddr3_top.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/i2c_dri.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/i2c_ov5640_rgb565_cfg.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/image_process.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/lcd_driver.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/lcd_rgb_top.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/line_shift_ram_8bit.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/matrix_generate_3x3_1bit.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/matrix_generate_3x3_8bit.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/ov5640_dri.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/picture_size.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/rd_id.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/rgb2ycbcr.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/image_process/template_matching.v" \
"C:/Users/Dell/Desktop/F/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_fun4_lcd.v" \

# compile glbl module
E:\\FPGA\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

